sudo: false
language: python
python:
    -"3.5" # TODO: change
branches:
    only:
        - master
        - tests
install:
    - python3 install setup.py
script:
    - py.test
after_success:
    echo "Success!"
after_failure:
    echo "Broken :("
